### 使用语言
# language: python
# python:
#   - "3.7.6" 
language: java

jdk:
  - oraclejdk8
  
dist: trusty

### sudo权限
sudo: required

### 内存配置
cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/pip
    - $HOME/downloads

### 过滤自动化构建的分支 
# 总共5类分支：master、integration-LSHT-1.2_0.11_1.31_1.2、individual-loader_1.2、individual-server_0.11、individual-hubble_1.3.1、individual-tools_1.1)
branches:
  only:
    - master
    - /^integration-.*$/
    - /^individual-.*$/
    
### 关闭默认git clone 代码
git:
  clone: false

### 安装python 组件依赖环境
before_install:
  - git clone --depth=50 --branch=$BRANCH_NAME https://github.com/lxb1111/test.git lxb1111/test
  - cd ${TRAVIS_DIR}
#   - sudo pip install -r requirements.txt
#   - sudo apt-get update
#   - apt search jdk
#   - sudo apt-get remove openjdk*
  - java -version
#   - sudo apt-get -y install openjdk-8-jdk



  
### git clone相关分支测试代码 && 安装部署graph组件
install:
  #   - if [ $BRANCH_NAME = default ]; then ./graph_install.sh $GRAPH_INSTALL; else echo "graph is not required to install..."; fi
  #   - python3 graph_install.py $BRANCH_NAME
  #   - sudo apt-get -y install tree
  #   - tree
  - java -version
  - git clone -b release-0.11 https://github.com/hugegraph/hugegraph.git
  - cd hugegraph/ && mvn compile -Dmaven.javadoc.skip=true | grep -v "Downloading\|Downloaded"
  
  
# ### 执行测试脚本
# script:
#   - python3 ${TRAVIS_DIR}/graph_test.py $BRANCH_NAME

# master中默认为最新的集成测试代码，各组件自动化代码默认都存储在分支上
env:
 global:   
   - BRANCH_NAME=master
   - TRAVIS_DIR=lxb1111/test/updateIntegration
    
