language: java

jdk:
  - oraclejdk8

dist: trusty

sudo: required

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/pip
    - $HOME/downloads

### 过滤自动化构建的分支 
# 总共5类分支：master、integration-LSHT-1.2_0.11_1.31_1.2、individual-loader_1.2、individual-server_0.11、individual-hubble_1.3.1、individual-tools_1.1)
branches:
  only:
    - master
    - /^integration-.*$/
    - /^individual-.*$/
    
### 关闭默认git clone 代码
git:
  clone: false

### 拉取测试代码 和 graph代码
before_install:
  - git clone --depth=50 --branch=$BRANCH_NAME https://github.com/lxb1111/test.git lxb1111/test
#   - ${TRAVIS_DIR}/graph_git.sh $BRANCH_NAME
#   - cd ${TRAVIS_DIR} && mkdir testEnv && cd testEnv/
  - git clone -b release-0.11 https://github.com/hugegraph/hugegraph.git

### 编译、安装 graph组件
install:
  - java -version
  - cd hugegraph/ && mvn clean package -Dmaven.test.skip=true | grep -v "Downloading\|Downloaded"
#   - ${TRAVIS_DIR}/graph_install.sh $BRANCH_NAME
  
before_script:
  - python3 --version
  - cd ${TRAVIS_DIR}
  - sudo pip install -r requirements.txt

script:
#   - python3 ${TRAVIS_DIR}/graph_test.py $BRANCH_NAME
  - echo 'script...'
  - true

after_script:
  - echo 'after_script...'

after_success:
  - echo 'after_success...'
      
# 环境变量的设置
env:
 global:   
   - BRANCH_NAME=master
   - TRAVIS_DIR=lxb1111/test/updateIntegration
