### 使用语言
language: python
### sudo权限
sudo: required

### 过滤自动化构建的分支
branches:
  only:
    - master
    - /^test-integration-.*$/
    - /^test-individual-.*$/

### 安装 hugegraph 组件依赖环境
before_install:
  - java -version
  # - sudo apt-get -yqq install software-properties-common
  # - sudo add-apt-repository ppa:webupd8team/java
  # - sudo apt-get -yqq update
  # - sudo apt-get -yqq install oracle-java8-installer
  # - sudo apt-get -yqq build-depgcc
  - gcc --version
# addons:
#   apt:
#     update: true  
  
# ### 安装部署 graph组件
install:
  - if [ $SERVER_INSTALL != false ]; then ./server_install.sh $SERVER_INSTALL; else echo "server is not required to install..."; fi
  - if [ $LOADER_INSTALL != false ]; then ./loader_install.sh $LOADER_INSTALL; else echo "loader is not required to install..."; fi
  - if [ $TOOLS_INSTALL != false ]; then ./tools_install.sh $TOOLS_INSTALL; else echo "tools is not required to install..."; fi
  - if [ $HUBBLE_INSTALL != false ]; then ./hubble_install.sh $HUBBLE_INSTALL; else echo "hubble is not required to install..."; fi
  
### 执行测试脚本
script: true




env:
 global:
   # *_INSTALL=false代表不需要安装相关组件；*_INSTALL=${branch_name} 代表部署该组件的该分支的代码
   - SERVER_INSTALL=false
   - LOADER_INSTALL=false
   - TOOLS_INSTALL=false
   - HUBBLE_INSTALL=false
   # 
   - BRANCH_NAME=test-0.11
   - TRAVIS_DIR=hugegraph-dist/src/assembly/travis
    

