### 使用语言
language: python
### sudo权限
sudo: required

### 过滤自动化构建的分支
branches:
  only:
    - master
    - /^test-integration-.*$/
    - /^test-individual-.*$/

### 安装 hugegraph 组件依赖环境
before_install:
  - sudo rm /etc/apt/sources.list.d/webupd8team-java.list
  - sudo apt-get -yqq install software-properties-common
  - sudo add-apt-repository -yqq ppa:webupd8team/java
  - sudo apt-get -yqq update
  - sudo apt-get -yqq install oracle-java8-installer
  - sudo apt-get -yqq build-depgcc
# addons:
#   apt:
#     update: true  
  
# ### 安装部署 graph组件
# install:
#   - if [ $IS_SERVER_INSTALL = true ]; then ./server_install.sh; else echo "server is not required to install..."; fi
#   - if [ $IS_LOADER_INSTALL = true ]; then ./loader_install.sh; else echo "loader is not required to install..."; fi
#   - if [ $IS_TOOLS_INSTALL = true ]; then ./tools_install.sh; else echo "tools is not required to install..."; fi
#   - if [ $IS_HUBBLE_INSTALL = true ]; then ./hubble_install.sh; else echo "hubble is not required to install..."; fi
  
### 执行测试脚本
script: true




#env:
#  - IS_SERVER_INSTALL= false
#  - IS_LOADER_INSTALL= false
#  - IS_TOOLS_INSTALL= false
#  - IS_HUBBLE_INSTALL= false
#   - BRANCH_NAME= test-0.11
#   - TRAVIS_DIR=hugegraph-dist/src/assembly/travis
    

